# -*- coding: utf-8 -*-
"""011172120_buffon's ndl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ol1kUQT6bQwQoRQ8lI8DCNJpohxv7lwl
"""

import random
import math
import matplotlib.pyplot as plt

d = int(input())
l = int(input())
hits = 0
n = 10000
miss_x = []
miss_y = []
hit_x = []
hit_y = []
for i in range(n):
  D = random.uniform(0,d/2)
  theta = random.uniform(0,3.1416)
  if D <= l/2 * math.sin(theta):
    hits += 1
    hit_x.append(theta)
    hit_y.append(D)
  else:
    miss_x.append(theta)
    miss_y.append(D)
fig, ax = plt.subplots()
ax.scatter(hit_x,hit_y,c='red')
ax.scatter(miss_x,miss_y,c='green')
ax.set_xlabel("Theta")
ax.set_ylabel("D")
ax.title.set_text("PI value")
ax.legend(labels=['hits','miss'])


pi = (2*l/d)*(n/hits)
print(pi)