# -*- coding: utf-8 -*-
"""continuous_simulation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-psMP6KZz5pvnepB5y2iFyLkIWZ1Ri7W
"""

import matplotlib.pyplot as plt


def distance(y_2, y_1, x_2, x_1):
    dis = ((y_2 - y_1)**2 + (x_2 - x_1)**2)**0.5
    return dis


def solve(old_t_x, old_t_y, t_x, t_y, d_x, d_y, dis, s):
    sin_theta = (old_t_y - d_y)/dis
    cos_theta = (old_t_x - d_x)/dis
    new_d_x = d_x + s*cos_theta
    new_d_y = d_y + s*sin_theta
    #dis = ((t_y-new_d_y)**2 + (t_x-new_d_x)**2)**0.5
    dis = distance(t_y, new_d_y, t_x, new_d_x)
    #print(sin_theta, cos_theta, new_d_x, new_d_y, dis)
    return new_d_x, new_d_y, dis


c_list = [(10, 10), (10, 10+7)]
b_list = [(0, 10)]
d_list = [(0, 0)]
a_list = [(10, 0)]
a, b, c, d = 3, 5, 7, 2
#ini_dis = ((t_list[0][1]-d_list[0][1])**2 + (t_list[0][0]-d_list[0][0])**2)**0.5
#ini_dis = distance(t_list[0][1],d_list[0][1],t_list[0][0], d_list[0][0])
dis_cb = [distance(c_list[0][1], b_list[0][1], c_list[0][0], b_list[0][0])]
dis_bd = [distance(b_list[0][1], d_list[0][1], b_list[0][0], d_list[0][0])]
dis_da = [distance(d_list[0][1], a_list[0][1], d_list[0][0], a_list[0][0])]
for i in range(0, 20-1):
    xxx = solve(*c_list[i], *c_list[i+1], *b_list[i], dis_cb[i], b)
    b_list.append(tuple(xxx[0:2]))
    dis_cb.append(xxx[2])

    xxx = solve(*b_list[i], *b_list[i+1], *d_list[i], dis_bd[i], d)
    d_list.append(tuple(xxx[0:2]))
    dis_bd.append(xxx[2])

    xxx = solve(*d_list[i], *d_list[i+1], *a_list[i], dis_da[i], a)
    a_list.append(tuple(xxx[0:2]))
    dis_da.append(xxx[2])
    #t_c_y = c_list[i+1][1] + c
    # print(t_c_y)
    c_list.append((10, c_list[i+1][1]+c))

c_hit, b_hit, d_hit = 0, 0, 0
for i in range(len(dis_cb)):
    print(i, dis_cb[i], dis_bd[i], dis_da[i], end=" ")
    if dis_cb[i] < 5:
        print("b shoots c", end=" ")
        c_hit += 1
    if dis_bd[i] < 5:
        print("d shoots b", end=" ")
        b_hit += 1
    if dis_da[i] < 5:
        print("a shoots d", end=" ")
        d_hit += 1
    print()
print("c got shot = ", c_hit)
print("b got shot = ", b_hit)
print("d got shot = ", d_hit)
# print(*dis_da)

c_x = [i[0] for i in c_list]
c_y = [i[1] for i in c_list]

b_x = [i[0] for i in b_list]
b_y = [i[1] for i in b_list]

d_x = [i[0] for i in d_list]
d_y = [i[1] for i in d_list]

a_x = [i[0] for i in a_list]
a_y = [i[1] for i in a_list]
# print(*c_x)
# print(*c_y)
# print(*d_x)
# print(*d_y)
# print(*d_list)
plt.plot(c_x, c_y, color="red", label="C path")
plt.plot(b_x, b_y, color="blue", label="b path")
plt.plot(d_x, d_y, color="green", label="d path")
plt.plot(a_x, a_y, color="yellow", label="a path")
plt.legend()
plt.show()
